export const metadata = {
  title: "Privacy Policy — Companion",
};

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-sm leading-relaxed text-white/80">
      <h1 className="mb-6 text-2xl font-semibold text-white">Privacy Policy</h1>

      <p className="mb-4 text-white/60">
        Last updated: {new Date().toISOString().slice(0, 10)}. Placeholder
        draft — have this reviewed by an attorney before public launch.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">1. What We Collect</h2>
      <p className="mb-4">
        Account and age-verification status; conversation history, including
        explicit chat content, and profiles/preferences used to personalize
        your experience; payment and billing metadata processed by our
        payment provider (we do not store full card numbers); and technical
        logs, including security events generated by our content moderation
        system.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">2. Age &amp; Identity Verification</h2>
      <p className="mb-4">
        We use a third-party identity verification provider to confirm you
        are a verified adult before granting access. Verification data is
        processed by that provider under its own privacy policy; we retain
        only the verification result and status, not the underlying
        identity documents.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">3. How Your Conversations Are Processed</h2>
      <p className="mb-4">
        The conversations you have on this platform, including explicit chat
        content, are processed by our AI service providers to generate
        responses. This includes text generation providers, and
        optionally third-party moderation and age-verification providers
        used to keep the platform safe and 18+. These providers process data
        under their own privacy and security terms, and we share only what
        is needed to provide the service.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">4. Content Moderation &amp; Security Logging</h2>
      <p className="mb-4">
        Every message you send is automatically screened by an automated
        safety system before and after AI processing. Messages that trigger
        a policy violation (including any reference to minors in a sexual
        context, or non-consensual content) are logged as a security event,
        which may include a truncated excerpt of the triggering message,
        for safety, compliance, and law-enforcement-cooperation purposes.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">5. Minors&apos; Data</h2>
      <p className="mb-4">
        This platform is strictly restricted to verified adults 18 years of
        age or older. We do not knowingly collect, store, or process the
        personal data of minors, and access is gated behind third-party
        age verification. If we become aware that a minor has provided us
        with personal data, we will delete it promptly.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">6. How We Use Your Data</h2>
      <p className="mb-4">
        To provide and improve the service, personalize your experience
        (including persona memory built from your conversation history and
        profiles), enforce our policies, process payments, and comply with
        legal obligations. We do not sell your personal data.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">7. Data Retention &amp; Deletion</h2>
      <p className="mb-4">
        You may delete individual conversations or request full deletion of
        your account and associated conversation history at any time via the
        support contact listed on the platform, subject to retention
        required for security/legal compliance records.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">8. Security</h2>
      <p className="mb-4">
        We apply standard security measures — encryption in transit, strict
        access controls, and limited staff access — to protect sensitive
        data such as verification status, billing metadata, and conversation
        history. No method of transmission over the internet is
        completely secure, but we work to protect your data and treat it
        with care.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">9. Contact</h2>
      <p className="mb-4">
        Questions about this Privacy Policy can be sent to the support
        address listed on the platform.
      </p>

      <p className="mt-10 text-white/60">
        &copy; {new Date().getFullYear()} Companion. All rights reserved.
      </p>
    </main>
  );
}