export const metadata = {
  title: "Terms of Service — Companion",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-sm leading-relaxed text-white/80">
      <h1 className="mb-6 text-2xl font-semibold text-white">Terms of Service</h1>

      <p className="mb-4 text-white/60">
        Last updated: {new Date().toISOString().slice(0, 10)}. Placeholder
        draft — have this reviewed by an attorney before public launch.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">1. Eligibility</h2>
      <p className="mb-4">
        This platform is strictly limited to verified adults 18 years of age
        or older (21+ in jurisdictions that require it). Access requires
        successful completion of third-party identity/age verification.
        Attempting to access this platform while underage, or attempting to
        misrepresent your age or identity, is a violation of these Terms and
        will result in immediate, permanent account termination and may be
        reported as required by law.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">2. Nature of the Service</h2>
      <p className="mb-4">
        All characters ("Personas") on this platform are entirely fictional
        and generated by artificial intelligence. No Persona is modeled on,
        based on, or intended to represent any real, living, or identifiable
        person. Any resemblance to a real person is coincidental and not
        intended. All text, audio, images, and video generated by this
        platform are synthetic AI output with no real human performers.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">3. Zero-Tolerance Content Policy</h2>
      <p className="mb-4">
        Content or requests involving, depicting, simulating, or referencing
        minors in any sexual context are strictly and permanently prohibited.
        Any detected attempt to generate such content results in immediate,
        permanent termination of your account and logging of the event. We
        cooperate fully with law enforcement regarding any such attempts.
        Non-consensual sexual content, real-world sexual violence, and
        non-consensual use of a real person's likeness are also strictly
        prohibited.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">4. Subscriptions &amp; Billing</h2>
      <p className="mb-4">
        Paid tiers unlock additional features as described at checkout.
        Subscriptions renew automatically until cancelled. Refund requests
        are handled per our payment processor&apos;s policies.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">5. Termination</h2>
      <p className="mb-4">
        We may suspend or terminate your access at any time for violation of
        these Terms, with or without notice, particularly for any violation
        of Section 3.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">6. Contact</h2>
      <p className="mb-4">
        Questions about these Terms can be sent to the support address listed
        on the platform.
      </p>
    </main>
  );
}
