export const metadata = {
  title: "Terms of Service — Companion",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-12 text-sm leading-relaxed text-white/80">
      <h1 className="mb-6 text-2xl font-semibold text-white">Terms of Service</h1>

      <p className="mb-4 text-white/60">
        Last updated: {new Date().toISOString().slice(0, 10)}. Placeholder
        draft — have this reviewed by an attorney before public launch.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">1. Eligibility</h2>
      <p className="mb-4">
        This platform is strictly limited to verified adults 18 years of age
        or older (21+ in jurisdictions that require it). Access requires
        successful completion of third-party identity/age verification.
        Attempting to access this platform while underage, or attempting to
        misrepresent your age or identity, is a violation of these Terms and
        will result in immediate, permanent account termination and may be
        reported as required by law.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">2. Nature of the Service</h2>
      <p className="mb-4">
        All characters (&ldquo;Personas&rdquo;) on this platform are entirely fictional
        and generated by artificial intelligence. No Persona is modeled on,
        based on, or intended to represent any real, living, or identifiable
        person. Any resemblance to a real person is coincidental and not
        intended. All text, audio, images, and video generated by this
        platform are wholly computer-generated synthetic AI output produced
        without any real human performers, and this platform and its content
        are accordingly exempt from the record-keeping requirements of 18
        U.S.C. &sect;2257 and 2257A.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">3. Content Policy</h2>

      <p className="mb-2 font-semibold text-white/90">3.1 Permitted Content</p>
      <p className="mb-4">
        This platform is an adult entertainment service. Verified adult users
        may explore explicit sexual content, erotic roleplay, kinks,
        fetishes, power dynamics, and sexual fantasies between fictional
        consenting adult personas.
      </p>
      <p className="mb-4">
        All personas are fictional AI characters, and no real human
        performers are involved in anything this platform produces. Every
        conversation, image, and audio output is wholly computer-generated
        by artificial intelligence and does not depict, model, or reference
        any real, identifiable person.
      </p>

      <p className="mb-2 font-semibold text-white/90">3.2 Prohibited Content</p>
      <p className="mb-4">The following content is strictly prohibited:</p>
      <p className="mb-4">
        (a) Content involving minors, or age-play in a sexual context, in
        any form. Any detected attempt to generate such content results in
        immediate, permanent termination of your account and logging of the
        event, and we cooperate fully with law enforcement regarding any
        such attempts.
      </p>
      <p className="mb-4">
        (b) Non-consensual sexual content, real-world sexual violence, or
        content depicting drugged, incapacitated, or otherwise
        non-consenting participants.
      </p>
      <p className="mb-4">
        (c) Non-consensual use of a real person&apos;s likeness, including
        deepfakes of real people and celebrity impersonation.
      </p>
      <p className="mb-4">
        (d) Content that is illegal under applicable law, or instructions
        for real-world harm, self-harm, or violence against people or
        animals.
      </p>
      <p className="mb-4">
        No other content is prohibited, provided all participants are
        fictional adults.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">Fantasy vs. Reality</h2>
      <p className="mb-4">
        All roleplay dialogue on this platform is generated for
        entertainment purposes only and depicts fictional scenarios between
        fictional adult personas. Nothing on this platform constitutes
        professional, medical, legal, or financial advice. Conversations are
        AI-generated and may contain imperfections, errors, or
        inconsistencies; they should never be treated as fact or guidance
        for real-world conduct.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">User Responsibility</h2>
      <p className="mb-4">
        You are responsible for your own use of the platform and must not
        request, attempt to generate, or share any of the prohibited content
        described in Section 3.2. Misuse of the platform, including repeated
        policy violations, results in termination of your account, and
        serious violations may be reported to law enforcement.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">4. Subscriptions &amp; Billing</h2>
      <p className="mb-4">
        Paid tiers unlock additional features as described at checkout.
        Subscriptions renew automatically until cancelled. Refund requests
        are handled per our payment processor&apos;s policies.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">5. Termination</h2>
      <p className="mb-4">
        We may suspend or terminate your access at any time for violation of
        these Terms, with or without notice, particularly for any violation
        of Section 3.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold text-white">6. Contact</h2>
      <p className="mb-4">
        Questions about these Terms can be sent to the support address listed
        on the platform.
      </p>

      <p className="mt-10 text-white/60">
        &copy; {new Date().getFullYear()} Companion. All rights reserved.
      </p>
    </main>
  );
}