import Link from "next/link";

export default function Footer() {
  return (
    <footer className="w-full border-t border-white/10 px-4 py-6 text-xs text-white/50">
      <div className="mx-auto flex max-w-3xl flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <p className="max-w-xl">
          18 U.S.C. &sect;2257 Exemption Statement: All characters, images, audio,
          and depictions on this platform are entirely computer-generated by
          artificial intelligence. No actual human performers appear in any
          content produced by this service, and no content depicts or
          references any real, identifiable person. Accordingly, this
          platform and its content are exempt from the record-keeping
          requirements of 18 U.S.C. &sect;2257 and 2257A, as no "actual sexually
          explicit conduct" by a real person is depicted.
        </p>
        <nav className="flex gap-4">
          <Link href="/legal/terms" className="hover:text-white/80">
            Terms
          </Link>
          <Link href="/legal/privacy" className="hover:text-white/80">
            Privacy
          </Link>
        </nav>
      </div>
    </footer>
  );
}
